### ISSUE TITLE
Issue upgrading from 1.0.2 to 1.1.0

### ISSUE THREAD

**Issue by SeanHayes** [furzeface/gulp-cache-bust#17]
I get this when running `gulp` after upgrading to 1.1.0:
```
fs.js:634
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/myuser/dev/web/assets//assets/dist/screens.min.css'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at Object.self.MD5 (/Users/myuser/dev/web/node_modules/cachebust/lib/cachebust.js:35:23)
    at Object.exports.busted (/Users/myuser/dev/web/node_modules/cachebust/lib/cachebust.js:58:40)
    at /Users/myuser/dev/web/node_modules/gulp-cache-bust/index.js:44:40
    at /Users/myuser/dev/web/node_modules/gulp-cache-bust/node_modules/graceful-fs/graceful-fs.js:78:16
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
```

**Comment by davinkevin** [comment]
Seems to be linked to https://github.com/furzeface/gulp-cache-bust/issues/15 ?

**Comment by fheidrich** [comment]
I had the same problem, 
My HTML has
    <link rel="stylesheet" href="/commonui/oraclejet-2.1.0/dist/css/alta/oj-alta.css" type="text/css"/>

My app is in a different folder but it uses content from a shared place in my server (/commonui)


I'm afraid I'll need to downgrade to 1.0.2

The stacktrace I get here is very similar:
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/fheidric/repos/iot/Server/ui/ProductionMonitoring/src/main/webapp//commonui/oraclejet-2.1.0/dist/css/alta/oj-alta.css'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.self.MD5 (/Users/fheidric/repos/iot/Server/ui/ProductionMonitoring/node_modules/cachebust/lib/cachebust.js:35:23)
    at Object.exports.busted (/Users/fheidric/repos/iot/Server/ui/ProductionMonitoring/node_modules/cachebust/lib/cachebust.js:58:40)

**Comment by SeanHayes** [comment]
Switching from `cachebust()` to `cachebust({basePath: '.'})` fixed it.
